export const GOT_EVENTS = "GOT_EVENTS"
export const LOGGED_IN = "LOGGED_IN"
export const LOGGED_OUT = "LOGGED_OUT"
export const ADDED_TO_CART = "ADDED_TO_CART"
export const DELETED_FROM_CART = "DELETED_FROM_CART"
export const GOT_CART = "GOT_CART"
export const GOT_ITEMS_BOUGHT = "GOT_ITEMS_BOUGHT"
export const CONFIRMED_CHECKOUT = "CONFIRMED_CHECKOUT"
export const EMPTIED_CART = "EMPTIED_CART"
export const RESET_CHECKOUT = "RESET_CHECKOUT"
export const GOT_SEATS_AVAIL = "GOT_SEATS_AVAIL"
export const GOT_ALL_SEATS_AVAIL = "GOT_ALL_SEATS_AVAIL"


