export const GOT_EVENTS = "GOT_EVENTS"
export const LOGGED_IN = "LOGGED_IN"
export const LOGGED_OUT = "LOGGED_OUT"
export const ADDED_TO_CART = "ADDED_TO_CART"
export const DELETED_FROM_CART = "DELETED_FROM_CART"
export const GOT_CART = "GOT_CART"
export const GOT_ITEMS_BOUGHT = "GOT_ITEMS_BOUGHT"
